### ISSUE TITLE
dispatch action outside the build function

### ISSUE THREAD

**Issue by GiacomoK** [brianegan/flutter_redux#101]
Hi,  
I am implementing fb login, and I need to dispatch action when the user logged in.  
I am not able to dispatch the action cause the function that logs in the user is outside the build function.

This is the code I am useing:

    import ...;

    class Menu extends StatefulWidget {
      @override
      _MenuState createState() => _MenuState();
    }

    class _MenuState extends State<Menu> {
      var facebookLogin = FacebookLogin();

      void onLoginStatusChanged(bool isLoggedIn, {profileData}) {
        // HERE I HAVE TO DISPATCH ACTION
      }

      void initiateFacebookLogin() async {
        var facebookLoginResult = await facebookLogin.logInWithReadPermissions(['email']);

        switch (facebookLoginResult.status) {
          case FacebookLoginStatus.error:
            onLoginStatusChanged(false);
            break;
          case FacebookLoginStatus.cancelledByUser:
            onLoginStatusChanged(false);
            break;
          case FacebookLoginStatus.loggedIn:
            var graphResponse = await http.get(
                'https://graph.facebook.com/v2.12/me?fields=name,first_name,last_name,email,picture.height(200)&access_token=${facebookLoginResult
                    .accessToken.token}');

            var profile = json.decode(graphResponse.body);
            print(profile.toString());

            onLoginStatusChanged(true, profileData: profile);
            break;
        }
      }

      @override
      Widget build(BuildContext context) {
        return StoreConnector<AppState, AppState>(
          converter: (store) => store.state,
          builder: (context, appState) {
            Widget _buildPage(isLoggedIn) {
              if (isLoggedIn) {
                return ListView(
                  children: <Widget>[
                    ListTile(
                      leading: Icon(Icons.watch),
                      title: Text('My settings'),
                    )
                  ],
                );
              } else {
                return Center(
                  child: RaisedButton(
                    child: Text("Login with Facebook"),
                    onPressed: () => initiateFacebookLogin(),
                  ),
                );
              }
            }
            return _buildPage(appState.isLoggedIn);
          },
        );
      }
    }

**Comment by jimsimon** [comment]
The simplest solution for you would be to change:
```dart
converter: (store) => store.state,
builder: (context, appState) {
  ...
}
```

to:
```dart
converter: (store) => store,
builder: (context, store) {
  ...
}
```

Then pass the store to `initiateFacebookLogin(...)` and then to `onLoginStatusChanged(...)`.  A better solution would be to define and use a view model class (like the examples do).
