### ISSUE TITLE
Switch route using flutter redux

### ISSUE THREAD

**Issue by rsmani** [brianegan/flutter_redux#105]
I am implementing a login screen using flutter and redux, the login state is stored in the redux store.After login, I want to smoothly navigate to another screen, lets call it the home screen. 

By going through other issues where routing is discussed in this repo, I adopted the following approach:

The Login screen calls a redux-thunk action which checks the login with the API. Once it verifies that the user has provided the correct credentials, it sets the logged in state in the redux store. I also store the fact that the API is being invoked in the state. When the Login screen renders, in case the state indicates that the API is being called, it shows a CircularProgressIndicator.

In the redux-thunk action after the API call is done and login is successful, I push the new route (to the home page).

The flow is fine - however, there is a flash where the login page changes from the circular progress indicator back to the login page (since state is not longer loading once API is done) - and then the home page is rendered.

This flash is very distracting and the flow does not seem smooth. Is there a standard pattern that I am missing to ensure that the login page does not re-render before showing the HomePage?

**Comment by brianegan** [comment]
Yep, this is an interesting problem with "reactive" approaches like this: Sometimes you don't want to display a specific state! In this case, you can use the `ignoreChange` property on the `StoreConnector`. It allows you to provide custom logic that let's you specify if a specific change to the store should be ignored.

In this case, you could ignore the change if the app is now logged in!
