### ISSUE TITLE
how to show a AlertDialog after reduce function

### ISSUE THREAD

**Issue by shyandsy** [brianegan/flutter_redux#106]
how to show a AlertDialog after reduce function？

when customer click button register, the RegisterAction will be received by middleware and the network operation will be performed. 

how can I show a dialog after this network operation, like show a error message like "the email has been registered" , "registeration successfully"

**Comment by brianegan** [comment]
Hey hey :) We're written up a document on the official redux readme that describes how to handle exactly this process!

https://github.com/johnpryan/redux.dart/blob/master/doc/async.md

**Comment by shyandsy** [comment]
@brianegan 
thank you and appreciate for the work

I will wait for that online
