### ISSUE TITLE
List -> detail flow

### ISSUE THREAD

**Issue by dawidhyzy** [brianegan/flutter_redux#107]
I'm new to Redux and Flutter. I have a dilemma on how to implement list -> detail flow. Currently, I'm passing selected list element to the detail page and the populating data on view. But I have a feeling that this is violating Redux rules where view should be updated according to app state. My idea is to introduce detail state field to app state and once user select list item dispatch action containing the item and set item in detail state. But I'm not sure if this is the best way to implement that.

I tried to find an answer to my question on GitHub but all of the examples are simple one-page apps.

**Comment by brianegan** [comment]
> Currently, I'm passing selected list element to the detail page and the populating data on view.

Hey, sorry -- was on a short vacay. Overall, the way I do it: Pass an `id` to the detail page. Then, the DetailPage can have a `StoreConnector` that connects to the Store and use a converter that finds the item in the Store given the Id. Something like this:


```dart
class AppState {
  final Map<int, User> users = {
    1: User(name: 'brianegan'),
    2: User(name: 'dawidhyzy'),
  };
}


class UserDetailPage extends StatelessWidget {
  final int userId;

  UserDetailPage({Key key, @required this.userId});

  @override
  Widget build(BuildContext context) {
    return StoreConnector<AppState, User>(
      converter: (store) => store.state.users[userId],
      builder: (context, user) => Text(user.name),
    );
  }
}
```
