### ISSUE TITLE
Initializing stuff with store.dispatch

### ISSUE THREAD

**Issue by Pacane** [brianegan/flutter_redux#11]
Hi,

I have this pattern where I initially injected a store instance in all my components using it (I wasn't aware of `new StoreProvider.of(...)`).

In my App, in some places, I also do 1 time initializations (ie: fetch data via `store.dispatch(...)`) in `initState()`. Previously, I could do it fine, because I had an instance of my Store.

Now I tried to move towards to `new StoreProvider.of(...)`, but I faced the issue where `context.inheritFromWidgetOfExactType(StoreProvider)` can't be called in `initState`. Is there a way to achieve that somehow?

Seems like the Flutter docs suggest that I use `didChangeDependencies()` but that is not called only 1 time.

Thanks

**Comment by brianegan** [comment]
Hey hey :) 

I can't speak to a custom implementation you've got going, but if you're using the "out of the box" `StoreConnector` and `StoreBuilder` Widgets, you can provide an `onInit` or `onDispose` function that will be fired when the Widget is first initialized and when it's disposed. Those would probably be my recommended way of initializing / disposing data at the right time.

To fix up your own implementation, the Trick I use: the `StoreConnector` widget itself doesn't access the `Store` using context within the `initState` method, but rather creates a new Widget in the `build` method where Context is available and passes the `Store` to that widget. Then the `Store` is available in the State class as the `widget.store` property.

https://github.com/brianegan/flutter_redux/blob/master/lib/flutter_redux.dart#L155

**Comment by Pacane** [comment]
The first option did it, thanks!

I wasn't aware of the `onInit` function.
