### ISSUE TITLE
About dispatch and async effect

### ISSUE THREAD

**Issue by my9074** [brianegan/flutter_redux#112]
I am doing an asynchronous operation through the [redux thunk](https://github.com/brianegan/redux_thunk) in the `LoginAction` and calling reducer . Then I want to call `Navigator` in `submitLoginForm` for page jumps. However, because dispatch seems to be unable to return a promise, the logic is unreasonable. Unless the `Navigator` is placed in the `redux thunk`. I have seen the [ simple-navigation-example](https://github.com/brianegan/flutter_redux/blob/simple-navigation-example/example/lib/main.dart) example . But I think the logic of route jumps should sometimes not be included in `redux`.

```dart
void submitLoginForm(BuildContext context) async {
       // ....
       _getStore()?.dispatch(LoginAction(_getStore(), context, userTag));
       
       // execute prior to the asynchronous operation
       Navigator.pushAndRemoveUntil(
          context,
          MaterialPageRoute(builder: (BuildContext context) => HomeState()),
          (Route<dynamic> route) => false,
       );
  }

new StoreBuilder<AppState>(builder: (context, store) {
     return RaisedButton(
     child: Text('Next'),
     onPressed: () => submitLoginForm(context),
   );
}),
```

**Comment by tudor07** [comment]
@my9074 have you found a solution?

**Comment by brianegan** [comment]
Redux thunk allows to return Futures now. This Should be working at this point!

**Comment by tudor07** [comment]
@brianegan do you think you can create an example on how to use it?
