### ISSUE TITLE
design problem

### ISSUE THREAD

**Issue by johanntony** [brianegan/flutter_redux#113]
When Flutter want to rebuild the dom,we need to setState and call _element.markNeedsBuild();
I want to know the redux how to rebuild the dom, is it also call setState or just full rendering the dom.

**Comment by brianegan** [comment]
Every component that is connected to the `Store` via a `StoreConnector` will be rebuilt when the store emits a change. It does this by listening to the Store's stream under the hood and calling `setState` for you automatically.

Therefore, it should not rebuild the entire Widget tree, it will only rebuild the components connected to the store. However, if you Connect to the Store at the top of your Widget tree, you may see larger rebuilds. Therefore, it's recommended you connect to the Store at "Leaf Widgets" as much as you can.

**Comment by craigomac** [comment]
An alternative library which is being archived (not sure why!) is https://github.com/leocavalcante/Flutter-ReduRx. That one has the advantage that you can specify that a widget only be rebuilt if a certain part of the state changes. Is there a way to achieve something similar with `flutter_redux`?

**Comment by brianegan** [comment]
@craigomac Yep!
