### ISSUE TITLE
Question:If I use TypedReducer，when will I use "Future"?

### ISSUE THREAD

**Issue by insipidness** [brianegan/flutter_redux#115]
class UserModel {
  String userName;  
  String password;   
  String token;     
  List roles;      
  UserModel({
    this.userName,
    this.password,
    this.token,
    this.roles,
  });
  factory UserModel.setUserInfo(String username,String password, String token,List roles) => UserModel(
    userName: username,
    password: password,
    token: token,
    roles: roles
  );
}
final userReducer = combineReducers<UserModel>([
    TypedReducer<UserModel, LoginByUserNameAction>(_loginByUserNameAction),
]);
Future<UserModel> _loginByUserNameAction(UserModel user, action) async {
  var result = await loginByUsername(action.user.userName, action.user.password);
  return UserModel.setUserInfo('123', 'password', 'token', []);
}
class LoginByUserNameAction {
  final UserModel user;
  LoginByUserNameAction(this.user);
}

**Comment by insipidness** [comment]
A piece of my mind：
button click >>> dispatch >>> action(now,i use Future at there) >>> update state
but,There are some problems here at
<pre>
final userReducer = combineReducers<UserModel>([
    TypedReducer<UserModel, LoginByUserNameAction>(_loginByUserNameAction),
]);
</pre>

**Comment by brianegan** [comment]
In general, `reducers` must be sync and they should not perform side-effects like this. In that case, use Middleware.

I'd recommend reading through the Docs we have on the Redux package to get an idea of how all these pieces fit together:

 https://github.com/johnpryan/redux.dart#docs
