### ISSUE TITLE
DOCS - fix example link

### ISSUE THREAD

**Issue by vvasc** [brianegan/flutter_redux#117]
Remove link to Todo app example in the section examples in README.md
https://github.com/brianegan/flutter_redux/blob/master/README.md#examples

**Comment by brianegan** [comment]
Fixed -- link changed but it's still alive!

**Comment by Nolence** [comment]
Can I ask why the example is no longer there? Currently trying to understand the library and from the description

> a more complete example, with persistence, routing, and nested state.

It felt like that was exactly what I was missing from the other two examples.

**Comment by brianegan** [comment]
Hey hey -- the link has been updated! We did a small reorg of that project and it broke the link on this repo, but I updated it a couple weeks ago. It can be found here: https://github.com/brianegan/flutter_architecture_samples/tree/master/redux
