### ISSUE TITLE
Switch how to change and get 

### ISSUE THREAD

**Issue by yikwing** [brianegan/flutter_redux#120]
![redux](https://i.loli.net/2019/03/23/5c959f97cb971.jpg)

I need to get the value of value and can change it

**Comment by brianegan** [comment]
In that case, you'll need to produce a ViewModel that contains two things: 1) The function to dispatch the action 2) The Value from the state.

```
class ViewModel {
  bool active;
  void Function(bool active) onChange;
 
  ViewModel(this.active, this.onChange);

  factory ViewModel.fromStore(Store<AppState> store) {
    return ViewModel(
      store.state.isSwitchActive,
      (bool active) => store.dispatch(ToggleSwitchAction(active))
    );
   }
```

**Comment by yikwing** [comment]
This solved my problem, thanks
