### ISSUE TITLE
Reset page widget after pop to initial state

### ISSUE THREAD

**Issue by H03in** [brianegan/flutter_redux#121]
Hi there!
thanks for amazing library.

i'm new to flutter and redux and have some problems.

1- is that true to store ui logic data like flag of toggle in app state???
2- if answer of 1 is true, when and where we must reset data of ui in app state, for example text of TextField that needs to validate, each time text changes must store to app state, so when user pops the page text still exist in appstate, of course i also remove the value when page ```onWillPop``` method calls(and it seems dirty :) ), but after pop page and returning to page TextField hast last value! does flutter destroy page after calling navigator pop method?

thanks.

**Comment by brianegan** [comment]
Hey there -- Where you store state is completely up to the requirements of your application. If making a change to a toggle affects different parts of your state tree, or if you need to rebuild different Widgets across your app, you can certainly put that data into the Store.

If the ui logic data is self-contained, you can store UI state in a StatefulWidget and dispatch actions with that data when it makes sense!

If you need to clean up data in your Store when you're done with a specific page, the best way is to use the `onInit` and `onDispose` callbacks on the `StoreConnector`. You could dispatch a `CleanupAction` inside `onDispose`, and the Reducer could handle that action to cleanup the necessary parts.
