### ISSUE TITLE
Application lifecycle

### ISSUE THREAD

**Issue by H03in** [brianegan/flutter_redux#123]
What is the best way to handle application lifecycle in redux like android onPause, onResume..?

**Comment by Taym95** [comment]
This has nothing to do with flutter_redux but it is flutter API, you can use [WidgetsBindingObserver](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html), Take a look in this [stackoverflow answer](https://stackoverflow.com/a/47571863/6117675).

**Comment by H03in** [comment]
Thanks @Taym95 .
