### ISSUE TITLE
Difference between documentation and implementation for `ignoreChange`. 

### ISSUE THREAD

**Issue by rostyslavroshak** [brianegan/flutter_redux#125]
```
/// To ignore a change, provide a function that returns true or false. If the
/// returned value is false, the change will be ignored.
```
The implementation is following:
```dart
if (widget.ignoreChange != null) {
      _stream = _stream.where((state) => !widget.ignoreChange(state));
    }
```
Let's say `ignoreChange` returns always `false`. 

```dart
 _stream = _stream.where((state) => !false);
```
Values will be picked, but documentation suggests, that value will be ignored.

I think the bug is documentation and it should be 
/// To ignore a change, provide a function that returns true or false. If the
/// returned value is **true**, the change will be ignored.

**Comment by brianegan** [comment]
Good call. I'll fix that up!

**Comment by ThinkDigitalSoftware** [comment]
Thanks. Can you push the change to pub, @brianegan?
