### ISSUE TITLE
Upgrade to AndroidX

### ISSUE THREAD

**Issue by dereklakin** [brianegan/flutter_redux#126]
Upgrade required to support [AndroidX](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility). I'll create a PR to fix.

**Comment by dereklakin** [comment]
The github_search example is dependent on rxdart, which itself needs to be upgraded to AndroidX for this to all work.

**Comment by brianegan** [comment]
Thanks again for the PR! Merged and fixed.
