### ISSUE TITLE
Any plans to make it work on the web platform?

### ISSUE THREAD

**Issue by ciokan** [brianegan/flutter_redux#128]
Struggling really hard to make this work on the web. I forked and removed the flutter sdk dependency because it was not working but now I have another issue with the `StoreProvider`: `The return type 'StoreProvider<AppState>' isn't a 'Widget', as defined by the method 'build'.`. I thought I can hack my way through the code but it's my 2nd day of flutter and I'm stuck.

This is my main code:

```
import 'package:flutter_web/material.dart';
import 'package:redux/redux.dart';
import 'package:flutter_redux/flutter_redux.dart';

import 'package:typely/store/state.dart';
import 'package:typely/store/reducers/reducers.dart';
import 'package:typely/components/sidebar/sidebar.dart';

void main() {
	runApp(TypelyApp());
}

class TypelyApp extends StatelessWidget {
	final store = Store<AppState>(
		appReducer,
		initialState: AppState.loading(),
	);

	@override
	Widget build(BuildContext context) {
		return StoreProvider(
			store: store,
			child: MaterialApp(
				title: 'Typely',
				debugShowCheckedModeBanner: false,
				theme: ThemeData(
					primarySwatch: Colors.blue,
				),
				home: HomePage(title: 'Typely'),
			));
	}
}

class HomePage extends StatelessWidget {
	HomePage({Key key, this.title}) : super(key: key);

	final String title;

	@override
	Widget build(BuildContext context) {
		return Scaffold(
			appBar: AppBar(
				title: Text(title),
				elevation: 2,
			),
			body: Row(
				children: <Widget>[
					Sidebar(),
				],
			),
		);
	}
}
```

The error is where `return StoreProvider(` is placed. Any ideas?

**Comment by Josemboa** [comment]
@ciokan, I have the same problem here. How did you solve it?

**Comment by ciokan** [comment]
cloned and tweaked: https://github.com/ciokan/flutter_redux

**Comment by komiljonovshohjahon** [comment]
I know it is too late to answer, but in the future, in case if someone needs it.

When you wrap the widget with _StoreProvider_ you must specify the _output_ of the state. So you must change **this**:

	@override
	Widget build(BuildContext context) {
		return StoreProvider(        //THIS IS CHANGED
			store: store,
			child: MaterialApp(
				title: 'Typely',
				debugShowCheckedModeBanner: false,
				theme: ThemeData(
					primarySwatch: Colors.blue,
				),
				home: HomePage(title: 'Typely'),
			));
	}
}

to **this:** 

	@override
	Widget build(BuildContext context) {
		return StoreProvider<AppState>(      //THIS IS CHANGED
			store: store,
			child: MaterialApp(
				title: 'Typely',
				debugShowCheckedModeBanner: false,
				theme: ThemeData(
					primarySwatch: Colors.blue,
				),
				home: HomePage(title: 'Typely'),
			));
	}
}

Thank you!
