### ISSUE TITLE
is old view model available to check for diff?

### ISSUE THREAD

**Issue by subhash279** [brianegan/flutter_redux#133]
Hi,
In react-redux componentDidUpdate, you can check for prevProps and current props and perform an action based on the difference.
Is it possible to do that here?
Thanks.

**Comment by Taym95** [comment]
You need to set distinct to true check [distinct code](https://github.com/brianegan/flutter_redux/blob/95e5c7f27aa5b9f5293f8fc2ccfb79081011b633/lib/flutter_redux.dart#L145)

**Comment by brianegan** [comment]
If you need to do something like that, you can always create a StatefulWidget, and inside the state class you can override the `didUpateWidget` method. This will be run when the Widget is rebuilt with new values!

**Comment by subhash279** [comment]
Hi, Thanks a lot for the suggestions. I actually used the StatefulWidget as you said.
