### ISSUE TITLE
Animations on state changes? 

### ISSUE THREAD

**Issue by naiveai** [brianegan/flutter_redux#140]
Since we don't have the previous `ViewModel` to compare to, I'm not entirely sure if it's possible to implement animations correctly in this system. For example, is it possible to know when a new item in a list has come and cleanly animate it in instead of it just kind of popping up?

**Comment by brianegan** [comment]
Hey there -- you can do the same thing that Widgets like the `Switch` or `CupertinoSwitch` do -- they are StatefulWidgets that override the `didUpdateWidget` method to check if new values are passed in. If it sees new values are passed in, it will perform an animation!

You can write Widgets that do the exact same thing. Example here: https://gist.github.com/brianegan/e1702d036d7525a41239b7e170d828b9

If that's helpful, I'll add that example to the repo!

**Comment by naiveai** [comment]
Ah yes, of course, that would work! Thanks a lot for that! And yeah, adding an example of that with reference to React's state-props matching would be pretty helpful.
