### ISSUE TITLE
Convert dispatch to lambda

### ISSUE THREAD

**Issue by andrasferenczi** [brianegan/flutter_redux#145]
The current implementation of the `dispatch` function looks like this:

```Dart
class Store<State> {
...
  void dispatch(dynamic action) {
    _dispatchers[0](action);
  }
...
}
```

Even though the same `Store` instance is used throughout the application, retrieving the `dispatch` function creates a new instance of the function every single time.

This code ...

```Dart
class Store {
  void dispatch() => print("test");
}

main() {
  final store = new Store();
  print(identical(store.dispatch, store.dispatch));
}
```

... prints out `false`.

See detailed discussion [here](https://stackoverflow.com/questions/16458199/why-does-dart-create-closures-when-referencing-a-method).

It would be great if `dispatch` was implemented as a lambda assignment, so that it could be used as a parameter for memoization.

*(That wouldn't be any breaking change of course)*

What do you think about this?

**Comment by brianegan** [comment]
Yo yo -- if that's an important feature, it can certainly be a non-breaking change! Just a heads up: That would require a change to the `redux` package itself, since this package merely provides Widgets to provide & consume a Redux store.
