### ISSUE TITLE
Using Refresh Indicator, triggers UI update on reaching top of the page and UI lags on scolling

### ISSUE THREAD

**Issue by bipin000** [brianegan/flutter_redux#149]
I have a listview inside a RefreshIndicator and whenever I scroll to the top and start swipe down again the logs show me whole UI data rebuilding in the widget meanwhile I dont see any difference on UI but a lag in scrolling down  

so my code looks like

The main container A statefull widget 

    class _HomePage extends State<StatefulWidget> {
    @override
    void initState() {
        super.initState();
    }

    @override
    Widget build(BuildContext context) {
        return StoreConnector<AppState, ViewModelFeed>(
            onInit: ((store) {
            store.dispatch(StoreOnboardingCategories(onboardingCategories: {}));
            }),
            converter: (Store<AppState> store) => ViewModelFeed.create(store),
            builder: (BuildContext context, ViewModelFeed viewModel) =>
                updateFeed(viewModel, context));
    }

    Widget updateFeed(ViewModelFeed _vm, BuildContext context) {
        return Scaffold(
            drawer: NaviationDrawer(),
            floatingActionButton: _floatingActionButton(context),
            appBar: MyAppBar(_vm).build(context),
            body: WillPopScope(
            onWillPop: () {
                DateTime now = DateTime.now();
                if (currentBackPressTime == null ||
                    now.difference(currentBackPressTime) > Duration(seconds: 2)) {
                currentBackPressTime = now;
                Toast.show(Strings.press_back_exit, context,
                    duration: Toast.LENGTH_SHORT, gravity: Toast.BOTTOM);
                Future.value(false);
                } else {
                showDialog(
                    context: context,
                    barrierDismissible: false,
                    builder: (BuildContext context) {
                        return AlertDialog(
                        title: Text(Strings.confirm_exit),
                        content: Text(Strings.are_sure_exit),
                        actions: <Widget>[
                            FlatButton(
                            child: Text(Strings.yes),
                            onPressed: () {
                                SystemNavigator.pop();
                            },
                            ),
                            FlatButton(
                            child: Text(Strings.no),
                            onPressed: () => Navigator.of(context).pop(),
                            )
                        ],
                        );
                    });
                }
            },
            child: Column(
                children: <Widget>[
                ExpandedSection(
                    expand: _vm.isCategoryExpanded,
                    child: FilterListWidget(_vm),
                ),
                Expanded(child: ListItem(page: Strings.home))
                ],
            ),
            ));
    }

An Item list class as a statefull widget used as expanded child in homepage and this list contains  RefreshIndicator and items list as child of refresh indicator.

So when I swipe down  it works fine but when I swipe back to top and again swipe down (delicately so that refresh indicator is not triggered) and then the UI lags for a moment, and I observed that the RPostWidget rebuilds

This happens only with refreshindicator removing it works prefect no lag or ui rebuild.
  
    class _ListItem extends State<ListItem> {
    final String page;
    bool paginate = false;
    var _scrollController = ScrollController();

    _ListItem(this.page);
    _scrollListner() {
        if (_scrollController.offset >=
                _scrollController.position.maxScrollExtent &&
            !_scrollController.position.outOfRange) {
        if (!paginate)
            setState(() {
            paginate = true;
            });
        StoreProvider.of<AppState>(context).dispatch(
            RefreshItemsAction(page: page, showLoading: true, isInit: false));
        }
    }

    @override
    Widget build(BuildContext context) {
        return StoreConnector<AppState, ViewModelFeed>(
        converter: (store) => ViewModelFeed.create(store),
        onInit: ((store) {
            print("---what is wrong here----");
            _scrollController.addListener(_scrollListner);
        }),
        onDispose: ((store) {
            _scrollController.dispose();
        }),
        builder: (BuildContext context, ViewModelFeed vm) {
            return vm.isLoading && !paginate
                ? Center(
                    child: CircularProgressIndicator(),
                )
                : loadFeed(vm, page, context, _scrollController);
        },
        );
    }

    Widget loadFeed(ViewModelFeed vm, String page, BuildContext context,
        ScrollController _scrollController) {
        List<ItemCard> feed = [];
        return RefreshIndicator(
            onRefresh: () {
            setState(() {
                paginate = false;
            });
            var action =
                RefreshItemsAction(page: page, showLoading: false, isInit: true);
            StoreProvider.of<AppState>(context).dispatch(action);
            return action.completer.future;
            },
            child: ListView(
            shrinkWrap: true,
            physics: AlwaysScrollableScrollPhysics(),
            controller: _scrollController,
            children: <Widget>[
                feed.length != 0
                    ? ListView(
                        shrinkWrap: true,
                        physics: ScrollPhysics(),
                        children: feed
                            .map((ItemCard item) => RPostWidget(
                                item: item,
                                model: vm,
                                sheetType: sheettype,
                                ))
                            .toList())
                    : Text("No feed in list"),
                Padding(
                    padding: EdgeInsets.all(50.0),
                    child: Align(
                        alignment: Alignment.center,
                        child: CircularProgressIndicator()
                        
                        ))
            ],
            ));
    }
    }

    class RPostWidget extends StatelessWidget {
    final ViewModelFeed model;
    final ItemCard item;
    final int sheetType;

    RPostWidget({this.model, this.item, this.sheetType});

    @override
    Widget build(BuildContext context) {
        return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
            _drawCardHeaderLabel(context),
            _drawCardHeader(context),
            _drawCardContent(context),
            Divider(),
            _drawCardActionButtons(context),
            Divider(),
        ],
        );
   }

**Comment by JohnBellSageCom** [comment]
I believe this is an issue with the refresh indicator. 

A fix for the underlying issue which caused this was commited as part of this pull request on flutter https://github.com/flutter/flutter/pull/53149. The fix will be in flutter releases 1.16.3 and highter.
