### ISSUE TITLE
Fix StoreProvider.of for Reified types

### ISSUE THREAD

**Issue by lwasylkowski** [brianegan/flutter_redux#15]
I'm repeatedly getting 

```
I/flutter ( 9311): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9311): The following NoSuchMethodError was thrown building StoreConnector<int, Store<int>>(dirty):
I/flutter ( 9311): The getter 'store' was called on null.
I/flutter ( 9311): Receiver: null
I/flutter ( 9311): Tried calling: store
```

error when trying to use `StoreBuilder` or `StoreConnector` in the hierarchy. My app widget builds the rest like this:

```
@override
Widget build(BuildContext context) {
  return new StoreProvider<int>(
    store: new Store<int>(
            (i, action) => i + 1,
        initialState: 0
    ),
    child: new MaterialApp(
      title: 'App',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new Scaffold(
          appBar: new AppBar(
            title: new Text("App"),
          ),
          body: new MainScreen(),
    ),
  );
}
```

I can't get it to work, I understand `StoreProvider` is a simple InheritedWidget, but even if I try to manually call `new StoreProvider.of(context)` in a widget down the tree, I get `null`. I don't understand, since I've created dead simple inherited widget and placed it instead of `StoreProvider` and I could fetch it with `of()` method without issues (I almost did a copy-paste from the StoreProvider class).

The `int` state and inline reducer is just a result of me trying to simplify the things as much as I can, with no luck. Any idea why would it be like this?

**Comment by brianegan** [comment]
Hrm, interesting case. 

I think the problem might be: you're constantly rebuilding a new Store in the `build` method and handing that off to the `StoreProvider`, and the library might not handling that properly.

I'll take a deeper look. For now, could you please try moving the Store out of the `build` method into an `initState` and see if it works?

**Comment by lwasylkowski** [comment]
I'm not sure what you mean, but I moved the app to a stateful widget, created the entire tree (starting from `StoreProvider` in state's build method, but passed `store` field created in `initState` -- still no luck.

I'll add that initially I created `store` field inline `final store = ...`, much like in your sample actually. If you don't have more ideas, maybe I'll clean it up/rewrite and paste entire app for you to run?

**Comment by brianegan** [comment]
Yah that would be great... I haven't run into that issue before :(

**Comment by lwasylkowski** [comment]
```
import 'package:flutter/material.dart';
import 'package:flutter_redux/flutter_redux.dart';
import 'package:redux/redux.dart';

void main() => runApp(new TestApp());

class TestApp extends StatelessWidget {

  final store = new Store<int>(
        (state, action) => state + 1,
    initialState: 0,
  );

  @override
  Widget build(BuildContext context) =>
      new StoreProvider<int>(
          store: this.store,
          child: new MaterialApp(
            title: "App",
            theme: new ThemeData(
              primarySwatch: Colors.blue,
            ),
            home: new Scaffold(
              appBar: new AppBar(
                title: new Text("App"),
              ),
              body: new MainScreen(),
            ),
          )
      );
}

class MainScreen extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return new StoreConnector<int, String>(
      converter: (state) => state.toString(),
      builder: (context, text) =>
      new Center(
        child: new Text(text),
      ),
    );
  }
}
```

Here it is. Only two new dependencies in pubspec:

```
redux: ^2.1.1
flutter_redux: ^0.3.5
```

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio
[✓] Android Studio
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
[!] VS Code (version 1.19.2)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```

**Comment by brianegan** [comment]
Yep, you found a bug! This is an interesting problem with how Dart reifies types, and my current solution doesn't quite work unfortunately ;(

For now, please use `new StoreProvider` instead of `new StoreProvider<int>` and it should work!

**Comment by brianegan** [comment]
As a heads up: Got a fix in the work. I'll try to push it up soon-ish!

**Comment by santiagofm** [comment]
I encountered the same issue with the example project and just found out it happens if i have the dart 2 preview enabled.. I'm not sure if it's the same issue but disabling the preview _fixes_ it

Cheers

**Comment by brianegan** [comment]
Thanks for the report! I'm actually working on a few changes that enforce the typing more strictly to fix both this bug and Dart2 support :)

**Comment by santiagofm** [comment]
Awesome !! keep up the good work!

**Comment by xrigau** [comment]
Same issue here, glad I'm not the only one 😅

Meanwhile I replaced the dependency in the `pubspec.yaml` file with:

```
  flutter_redux:
    git:
      url: git://github.com/brianegan/flutter_redux.git
      ref: 0.4.0
```

and everything works again, thanks for your work @brianegan 💯

**Comment by brianegan** [comment]
Sure thing! Sorry for the delay in publishing the new version, test coverage isn't quite working with Dart 2 and I'd like to hold off until that's fixed.

**Comment by xrigau** [comment]
Will do!
