### ISSUE TITLE
Add link to pub in github title link

### ISSUE THREAD

**Issue by bradyt** [brianegan/flutter_redux#166]
I am developing some muscle memory that when I am browsing a Dart package in Github or https://pub.dev/, I am able to easily navigate between Dart packages in the two, because frequently packages have links to the other in each of the two pages.

For example, if I am at https://pub.dev/packages/built_collection, there is a link to https://github.com/google/built_collection.dart, and vice versa. This makes it easy to quickly browse source code, issues, API docs, etc, without performing another internet search.

Please add link to https://pub.dev/packages/flutter_redux next to Github title.

**Comment by brianegan** [comment]
Both link to each other :)

**Comment by bradyt** [comment]
I think the Github desktop layout no longer puts the website link near the title, but below the about section.

I meant to have the link there, below the about, as this is a somewhat common idiom I am seeing in pub.dev packages, but readme works.
