### ISSUE TITLE
'store != null' is not true / failed assertion 

### ISSUE THREAD

**Issue by mcolakogluj** [brianegan/flutter_redux#168]
Hi
I get a chronic error in 'flutter_redux.dart' file.
It gives the same error in all my flutter redux apps.
How can I solve this?

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter ( 5402): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5402): The following assertion was thrown building MyApp(dirty):
I/flutter ( 5402): 'package:flutter_redux/flutter_redux.dart': Failed assertion: line 21 pos 16: 'store != null': is
I/flutter ( 5402): not true.
I/flutter ( 5402):
I/flutter ( 5402): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5402): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5402): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5402):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5402):
I/flutter ( 5402): The relevant error-causing widget was:
[38;5;248mI/flutter ( 5402):   MyApp[39;49m
I/flutter ( 5402):
I/flutter ( 5402): When the exception was thrown, this was the stack:
[38;5;248mI/flutter ( 5402): #2      new StoreProvider[39;49m
[38;5;248mI/flutter ( 5402): #3      MyApp.build[39;49m
[38;5;244mI/flutter ( 5402): #4      StatelessElement.build[39;49m
[38;5;244mI/flutter ( 5402): #5      ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 5402): #6      Element.rebuild[39;49m
[38;5;244mI/flutter ( 5402): #7      ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 5402): #8      ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 5402): #9      Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 5402): #10     Element.updateChild[39;49m
[38;5;244mI/flutter ( 5402): #11     RenderObjectToWidgetElement._rebuild[39;49m
[38;5;244mI/flutter ( 5402): #12     RenderObjectToWidgetElement.mount[39;49m
[38;5;244mI/flutter ( 5402): #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>[39;49m
[38;5;244mI/flutter ( 5402): #14     BuildOwner.buildScope[39;49m
[38;5;244mI/flutter ( 5402): #15     RenderObjectToWidgetAdapter.attachToRenderTree[39;49m
[38;5;244mI/flutter ( 5402): #16     WidgetsBinding.attachRootWidget[39;49m
[38;5;244mI/flutter ( 5402): #17     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>[39;49m
[38;5;244mI/flutter ( 5402): #26     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:384:19)[39;49m
[38;5;244mI/flutter ( 5402): #27     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:418:5)[39;49m
[38;5;244mI/flutter ( 5402): #28     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)[39;49m
I/flutter ( 5402): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter ( 5402):
I/flutter ( 5402): ════════════════════════════════════════════════════════════════════════════════════════════════════
`

`void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final Store<StateApp> store;

  MyApp({this.store});

  @override
  Widget build(BuildContext context) {
    return StoreProvider(
      store: store,
      child: MaterialApp(
        title: 'StarterApp',
        navigatorObservers: [routeObserver],
        navigatorKey: Keys.navigatorKey,
        onGenerateRoute: (RouteSettings settings) => _getRoute(settings),
        home: ScreenLogin()
      ),
    );
  }

  MaterialPageRoute _getRoute(RouteSettings settings) {
    switch (settings.name) {
      case AppRoutes.login:
        return MainRoute((ScreenLogin()), settings: settings);
    }
  }

  Store<StateApp> createStore() {
    return Store<StateApp>(
      reducerApp,
      initialState: StateApp.initial(),
      middleware: createStoreMiddleware(),
    );
  }
}`

and this is my dart code.

**Comment by brianegan** [comment]
Right now, your Widget accepts a `store` in it's constructor and passes it to the `StoreProvider` Widget. That all looks good. The problem: You're never calling your `createStore` function in the `main` function to create the Store and pass it to your Widget.

Therefore, you're not passing the Store into your `MyApp` Widget, and therefore passing a `null` store into the `StoreProvider`. To fix the issue, you need to change your main function to this:

`void main() => runApp(MyApp(store: createStore()));`
