### ISSUE TITLE
search_screen err

### ISSUE THREAD

**Issue by stational** [brianegan/flutter_redux#173]
i get an error in  search_screen.dart 
the error render at :

  Widget _buildVisible(SearchState state) {
    if (state is SearchLoading) {
      return SearchLoadingView();
    } else if (state is SearchEmpty) {
      return SearchEmptyView();
    } else if (state is SearchPopulated) {
         /// ide show that the state.resultdoes not match the require param
      return SearchPopulatedView(state.result);     
    } else if (state is SearchInitial) {
      return SearchInitialView();
    } else if (state is SearchError) {
      return SearchErrorWidget();
    }

**Comment by brianegan** [comment]
fixed any errors with example and latest version
