### ISSUE TITLE
Middleware creation failure does not throw error

### ISSUE THREAD

**Issue by elvisun** [brianegan/flutter_redux#178]
For the following code:
```dart
List<Middleware<AppState>> createMiddlewares() {
  final onFetchWishListMiddleware = _onFetchWishList();

  return [
    TypedMiddleware<AppState, FetchWishListAction>(onFetchWishListMiddleware),
  ];
}

Middleware<AppState> _onFetchSomething(SomethingService service) {
  return (Store<AppState> store, action, NextDispatcher next) async* {
    next(action);

    var user = selectors.getCurrentUser(store.state);

    service.list().listen((List<Something> items) {
      store.dispatch(FetchSomethingSuccessAction(items));
    });
  };
}
```

I accidentally put in `async*` which shouldn't be there, then this action's middleware and reducer wouldn't run, but it also didn't throw any error. Are we able to provide `Middleware` with a better type so we get warnings on things like this early?

**Comment by brianegan** [comment]
Hey there -- that's definitely a valid question, but would you mind opening this issue up on the `redux.dat` lib? https://github.com/johnpryan/redux.dart/issues

This library only hooks that library up to Flutter, and that's where the middleware is defined :)

**Comment by elvisun** [comment]
sure thing, thanks Brian!
https://github.com/johnpryan/redux.dart/issues/58
