### ISSUE TITLE
Store access in init

### ISSUE THREAD

**Issue by kentcb** [brianegan/flutter_redux#18]
Sorry, me again :)

Another question: what would be the correct way to reset some state prior to entering a given view? Imagine a form in the app that should reset whenever the user starts it. But it's a multi-page form, so they can also return to the start via the back button (which should _not_ reset the data). Therefore, I need to send a `ResetAction` during the `init` stage of the page.

However, achieving this seems problematic. The only way I know of obtaining the current store is:
```dart
new StoreProvider<AppState>.of(context).store
```
But this doesn't work during `init`:
```
The following assertion was thrown building _ModalScopeStatus(active, can pop):
I/flutter (13145): inheritFromWidgetOfExactType(StoreProvider) was called before
I/flutter (13145): _XXX.initState() completed.
I/flutter (13145): When an inherited widget changes, for example if the value of Theme.of() changes, its dependent
I/flutter (13145): widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor
I/flutter (13145): or an initState() method, then the rebuilt dependent widget will not reflect the changes in the
I/flutter (13145): inherited widget.
I/flutter (13145): Typically references to to inherited widgets should occur in widget build() methods. Alternatively,
I/flutter (13145): initialization based on inherited widgets can be placed in the didChangeDependencies method, which
I/flutter (13145): is called after initState and whenever the dependencies change thereafter.
```
I don't think `didChangeDependencies` is what I want, because then the data could reset in other circumstances.

I also considered having the reset just before the code that routes the user to the page. That totally works, and is what I've been running with for a while (and will have to continue doing so for now). However, I was trying to move away from this because it means one must remember to dispatch the action before routing. When you have multiple parts of the application routing to that same page, each of those parts must remember (or the routing must be abstracted/extracted in some fashion).

Any thoughts on this?

**Comment by brianegan** [comment]
Hey hey :) Always good questions, @kentcb. Really interesting, thanks for posting these issues! Please keep doing so!

Yes, that's a tricky one. I have two methods on the `StoreConnector` and `StoreBuilder` widgets:

`onInit` and `onDispose`. E.g. 

```dart
return new StoreConnector(
  onInit: (store) => store.dispatch(new InitAction()),
  onDispose: (store) => store.dispatch(new DisposeAction()),
  converter: ...,
  builder: ...,
}
```

Does this work for your use case? If not, It's kind of a funny hack the way it works: `StoreConnector` builds a `StatefulWidget` under the hood. `StoreConnector` grabs the `Store` in the build method and passes it to the StatefulWidget, so it's available in the `initState` method. You could follow a similar approach.

**Comment by kentcb** [comment]
Oh, that's _perfect_ for my use case. I wasn't aware of those callbacks - super useful, thanks!
