### ISSUE TITLE
StoreConnector rebuilds widget even after navigating to a different screen while using GlobalKey<NavigatorState> for navigation

### ISSUE THREAD

**Issue by uhbsksingh** [brianegan/flutter_redux#180]
The issue solved after setting `rebuildOnChange: false`. Obviously, but I need the Widget to update when there is change in state. The issue is, the Widget still builds after navigating to a different screen while using `GlobalKey<NavigatorState>` for navigation. I tried using the `Navigator` for navigation and the issue is gone but I cannot do that because I need to navigate from my Middlewares.

My code is based on [Timy Messenger](https://github.com/janoodleFTW/timy-messenger).

**To begin with the flow. I dispatch the `SignOutAction` from a separate `SignOutButtonWidget`.**
`onPressed: () {
        StoreProvider.of<AppState>(context).dispatch(SignOutAction());
      },`

**The Middleware basically does the following.**
`await authService.appUserSignOut();`
`cancelAllSubscriptions();`
`store.dispatch(SignOutSuccessAction());`

**First**, the `appUserSignOut()` calls the Firebase me `signOut()` method. I have a listner setup too. I've setup Middlewares for navigation. `AppNavigateAction()` dispatches the navigation action.
```
 authService.getAuthenticationStateChange().listen((firebaseUser) {
      if (firebaseUser == null) {
        store.dispatch(AppNavigateAction(
            navigationRoute: AppNavigationRoutes.welcomeScreen));
      } else {
        store.dispatch(OnAuthenticatedAction(firebaseUser: firebaseUser));
      }
    });
```
```
Middleware<AppState> _appNavigate(GlobalKey<NavigatorState> navigatorKey) {
  return (Store<AppState> store, dynamic dynamicAction,
      NextDispatcher next) async {
    final action = dynamicAction as AppNavigateAction;
    next(action);

    navigatorKey.currentState.pushReplacementNamed(action.navigationRoute);
   
  };
}
```

**Second**, I also have streams set up for other data sources which needs to be canceled when logged out by `cancelAllSubscriptions()`.

**Lastly**, ` SignOutSuccessAction()` clears up all the state to initial values.

**Now, I have a `StoreConnector` the builds  the UI. Lets say `ProfileScreen`**
```
StoreConnector<AppState, _ViewModel>(
      converter: (Store<AppState> store) => _ViewModel.create(store),
      rebuildOnChange: false,
      builder: (
        BuildContext context,
        _ViewModel viewModel,
      ) =>
            Scaffold(
        backgroundColor: Colors.grey[200],
        body: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Text(viewModel.firestoreAppUser.data.firstName),

                  //Dispatches SignOutAction(). Shown in the first code snippet.
                  LogoutButtonWidget(),
             ),
        )
);

```

So the issue I'm having, I tried debugging through the code and everything is working as they are supposed to. The new page, `LoginScreen`,  does get loaded into the screen but for a brief the error box page is shown complaining about the null values is the viewModel. It's also seen in the logs. The issue is gone if I add `rebuildOnChange: false`, but that's not what I want.

I tried using Flutter's `Navigator`, it works. The `LoginScreen` loads without `ProfileScreen` being rebuild. My understanding is, it has something to do with how two different ways to navigate. I'm not being able to get around this. Would be a great help if anyone could recommend a better way to do this. Thank you.

**Comment by muzzah** [comment]
Having a similar issue but it seems this library is dead as the issues are piling up, maybe its time to move on from this library since it doesnt seem to be moving forward

**Comment by brianegan** [comment]
When navigating screens, Flutter will always call the `build` method for the old and new Screen. This is important for things like animations. 

In this case, the old page is built as it exits the Screen during an animation. This problem isn't unique to redux -- if you listen to a ChangeNotifier on both screens and you null out a `Profile` value that you're displaying, you run into the same issue.

So how do you solve this? `ignoreChange`. You can see an example of exactly how this works on the Flutter Architecture Samples: https://github.com/brianegan/flutter_architecture_samples/blob/master/redux/lib/containers/todo_details.dart#L22

In that case, a Todo can be deleted from the Details Screen. If the ViewModel sees the Todo is no longer present, it does not run the `build` method.
