### ISSUE TITLE
How to reset AppState in redux when logout ?

### ISSUE THREAD

**Issue by khaitq7** [brianegan/flutter_redux#181]
Dear Sir/Madam .
The first , thank for your library .
Now , I am having issue when logout , I want reset all appstate in my app .
But I am confusing do this problem .
It very wonderful when you support or give to me solve for this .

Thank you so much

**Comment by AhmedNourJamalElDin** [comment]
+1

**Comment by julienzarka** [comment]
Just create a new action like ResetAppAction and when reducing it return a new State.

```
AppState recuder(AppState currentState, Object action) {
  if (action is ResetAppAction) {
    return AppState();
  }
   // handle other actions here ...
}
```
