### ISSUE TITLE
How to implement Redux with Thunk action, HTTP and Navigation?

### ISSUE THREAD

**Issue by darkfoxdx** [brianegan/flutter_redux#183]
First of all, thank you for making this great library. I hope this is the appropriate place to post this.

I'm very new to Flutter but I've had experience learning native Android. I quite enjoy Flutter but I'm unable to wrap my head around building the architecture for my app.

I'm using Redux, Redux persist, Thunk and HTTP. 

So my thunk action will dispatch a loading action and will dispatch a complete action or error action. 

So I need to call a Login API, call a Profile API if successful. If Profile exists, go to home screen, else go to create profile screen.

Currently putting the navigation at onDidChange but I quickly figured that was a really bad place to put it. 

I would like some advice on this. This issue has been gnawing at me. Thank you.

**Comment by chattertechno** [comment]
There is a library called redux thunk in pub dev it has the same thing that your asking.
You will call the API in a ThunkAction passing the Current app state and then dispatch the action in your way either successful or unsuccessfully. Here is a link to it https://pub.dev/packages/redux_thunk
