### ISSUE TITLE
Question: What is the difference btw flutter_redux and flutter_greencat? Which one should I choose?

### ISSUE THREAD

**Issue by sgon00** [brianegan/flutter_redux#2]
Hi, I don't know if I could ask a question in issues. If not, I am very sorry about this.
I am new to flutter and mobile development. 
The `Purpose` of this project in `README.md` is very well written and I am glad the author wrote it. But I am still confused the difference between `flutter_redux` and `flutter_greencat`. They are created by the same author and the README.md mentions each other. I googled greencat and find out it is a port of redux from reactjs to Dart. In another word, it means greencat in dart is redux. But now, they become two different projects  flutter_redux and flutter_greencat. I am wondering which one I should choose and will both projects well supported in the near future?

PS: can I use flutter_redux in production? since it's a very new project, I am wondering if it's stable to be used in produciton.

Thank you very much for your help.

**Comment by brianegan** [comment]
Ack, so sorry I missed this issue! Not sure how that happened :(

Greencat is a different Redux library, and `flutter_greencat` is meant to work with that library instead. Greencat had a bit more wind beneath it's sails at first, but the author of Greencat said he was going to change up Greencat to be more experimental, so I stopped supporting `flutter_greencat` as much and focused on a more "plain" version of Redux.

For a more stable, well-maintained lib, please go with this one!

With regards to production-readiness, it's a well-tested library and I'm actively trying to ensure it covers all use cases. That said, it's still pre-1.0, which is a warning that I might find bugs / use cases I hadn't considered and need to change this lib to make those work. Like all of Flutter, it's probably good enough to use in production, but I don't feel good enough to call it a 1.0 just yet.

**Comment by sgon00** [comment]
Thanks a lot for the detail reply, explanation and your hard work. :)
