### ISSUE TITLE
store dispatch method cause rebuild unexpectedly 

### ISSUE THREAD

**Issue by Nerogee** [brianegan/flutter_redux#201]
I use flutter_redux along with saga middleware. I notice that this store.dispatch method will cause widget rebuild even there is not setState explicitly called.

I used the StoreConnector like this
`Widget build(BuildContext context){

  print('This widget is built');
  return StoreConnector(
    converter: _ViewModel.fromStore,
    builder: (BuildContext context, vm){
       return MyWidgetHere();
   }
  )
}`
 

From what I observed, the dispatch method will trigger the rebuild process once it's called. Or maybe I didn't follow the best practice?

**Comment by brianegan** [comment]
Hey there -- please add `distinct: true` to your StoreConnector and ensure the `_ViewModel` class implements `==`. That should prevent the Widget from rebuilding!
