### ISSUE TITLE
onWillChange and onDidChange called twice after state update

### ISSUE THREAD

**Issue by Lyba97** [brianegan/flutter_redux#238]
I am having an issue with StoreConnector. I have a login page with a button that shows a popup if a specific condition is met. I have put the condition variable in the Store. When that variable turns true only then should the popup show. Every time there is a change in the state this onWillChange is called twice. I do not want it to run twice as my other logic also runs twice on state change. I am adding a screenshot of some print log that confirms that the method is called twice on each change. 
<img width="845" alt="Screenshot 2022-08-27 at 4 01 28 PM" src="https://user-images.githubusercontent.com/63864699/187027443-fa766f8e-b62b-4386-aac6-8fad2e2e30e8.png">

**Comment by brianegan** [comment]
Thanks for the report. From the print statements, I can see that
onWillChange is indeed called twice. However, it's hard to debug this issue
with a screenshot.

That could happen for a number of reasons. For example, do you have two
onWillChange callbacks in different parts of your app?

Therefore, do you have a small bit of code you can share which reproduces
the issue? I have some tests in place that verify onWillChange is only
called once, but I might have missed an edge case.

A small, reproducible sample app or bit of code is the only way I could
help discover the issue.

Thanks!

**Comment by Lyba97** [comment]
Hi, @brianegan Thank you for your response. I got to know that I was not overriding == and hashcode methods for the VM and hence `onWillChange` and `onDidChange` were being called twice. 
It is solved by overriding the methods in the relevant ViewModel class when distinct is true. You can mark it as complete :)
