### ISSUE TITLE
Error thrown when using Dart 2 Preview

### ISSUE THREAD

**Issue by mjohnsullivan** [brianegan/flutter_redux#24]
I tried to get the [flutter-redux example](https://pub.dartlang.org/packages/flutter_redux#-example-tab-) working with the Dart 2 preview, but I get the following error when I try to run it:

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building StoreConnector<int, String>(dirty):
The getter 'store' was called on null.
Receiver: null
Tried calling: store
When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core/object_patch.dart:46:5)
#1      StoreConnector.build (package:flutter_redux/flutter_redux.dart:156:44)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)

Works fine when not activating the preview. The Flutter build I'm using is:

Flutter 0.1.5 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3ea4d06340 (3 weeks ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759

**Comment by brianegan** [comment]
Hey, thanks for the report! I've got a PR up to fix Dart 2.0: #20

However, it's currently blocked by https://github.com/flutter/flutter/issues/15681
