### ISSUE TITLE
Wrong version code deployed (0.3.6 instead of 0.4.0)

### ISSUE THREAD

**Issue by xrigau** [brianegan/flutter_redux#27]
First of all, thanks for putting the effort to release a version of `flutter_redux` that support Dart 2 this quickly, really appreciated 💯 

Now, the issue: In the repo it looks like the latest version of the package that's been released is `0.4.0` but actually in pub it got released as `0.3.6` https://pub.dartlang.org/packages/flutter_redux/versions/0.3.6

Version `0.3.6` of the `flutter_redux` package seems to work well with Dart 2, so It should probably be deleted and re-released as 0.4.0, as people can get confused as to which version to use for Dart 1 and Dart 2.

**Comment by brianegan** [comment]
@xrigau Thanks for writing in!

Don't worry: 0.3.6 was meant to be the last version that supports Dart 1! I've just finished up the Dart 2 migration and publishing 0.4.0 shortly.

**Comment by brianegan** [comment]
Just did some double-checking and everything looks good. For Dart2 support, please use 0.4.0

**Comment by xrigau** [comment]
Ah! I was confused because 0.3.6 seems to work well with Dart2 whereas 0.3.5 didn't 😅 

Anyway thanks for releasing 0.4.0 🎉

**Comment by brianegan** [comment]
@xrigau Weird haha, 0.3.6 was totally broken on my machine with Dart 2 :P

I think there are some serious Dart 2 👻 👻 👻  right now

**Comment by xrigau** [comment]
Yeah maybe it didn't update the dependency correctly (as I had been using the dependency from the `0.4.0` git branch), dart2 shenanigans ¯\\_(ツ)_/¯
