### ISSUE TITLE
NoVersionException is throwing while trying to install

### ISSUE THREAD

**Issue by ansal-exp** [brianegan/flutter_redux#31]
Hi, I am getting an error while trying to install this lib. I don't get the exact reason why this happens.

`[flutter_redux_boilerplate] flutter packages get
Running "flutter packages get" in flutter_redux_boilerplate...
Package flutter_redux has no versions that match 0.4.1 derived from:
- flutter_redux_boilerplate depends on version 0.4.1
---- Log transcript ----
FINE: Pub 2.0.0-dev.16.0
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - cupertino_icons ^0.1.0 from hosted (cupertino_icons) (locked to 0.1.1)
    | - flutter any from sdk (flutter) (locked to 0.0.0)
IO  : Get versions from https://pub.dartlang.org/api/packages/flutter_redux.
IO  : HTTP GET https://pub.dartlang.org/api/packages/flutter_redux
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: E1E8D34B-A97D-46A3-B242-DD2F405A3190
    | X-Pub-Environment: flutter_cli:get
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/flutter_redux
    | took 0:00:00.757222
    | transfer-encoding: chunked
    | date: Thu, 29 Mar 2018 04:13:37 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/redux.
IO  : HTTP GET https://pub.dartlang.org/api/packages/redux
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: E1E8D34B-A97D-46A3-B242-DD2F405A3190
    | X-Pub-Environment: flutter_cli:get
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/redux
    | took 0:00:00.765028
    | transfer-encoding: chunked
    | date: Thu, 29 Mar 2018 04:13:37 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: * start at root
SLVR: | cupertino_icons 0.1.1 from hosted is locked
SLVR: | * select cupertino_icons 0.1.1 from hosted
SLVR: | | flutter 0.0.0 from sdk is locked
SLVR: | | * select flutter 0.0.0 from sdk
SLVR: | | | collection 1.14.5 from hosted is locked
SLVR: | | | * select collection 1.14.5 from hosted
SLVR: | | | | flutter_test 0.0.0 from sdk is locked
SLVR: | | | | * select flutter_test 0.0.0 from sdk
SLVR: | | | | | * select pub itself
SLVR: | | | | | | args 1.2.0 from hosted is locked
SLVR: | | | | | | * select args 1.2.0 from hosted
SLVR: | | | | | | | async 2.0.3 from hosted is locked
SLVR: | | | | | | | * select async 2.0.3 from hosted
SLVR: | | | | | | | | barback 0.15.2+14 from hosted is locked
SLVR: | | | | | | | | * select barback 0.15.2+14 from hosted
SLVR: | | | | | | | | | boolean_selector 1.0.2 from hosted is locked
SLVR: | | | | | | | | | * select boolean_selector 1.0.2 from hosted
SLVR: | | | | | | | | | | charcode 1.1.1 from hosted is locked
SLVR: | | | | | | | | | | * select charcode 1.1.1 from hosted
SLVR: | | | | | | | | | | | cli_util 0.1.2+1 from hosted is locked
SLVR: | | | | | | | | | | | * select cli_util 0.1.2+1 from hosted
SLVR: | | | | | | | | | | | | convert 2.0.1 from hosted is locked
SLVR: | | | | | | | | | | | | * select convert 2.0.1 from hosted
SLVR: | | | | | | | | | | | | | crypto 2.0.2+1 from hosted is locked
SLVR: | | | | | | | | | | | | | * select crypto 2.0.2+1 from hosted
SLVR: | | | | | | | | | | | | | | csslib 0.14.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | * select csslib 0.14.1 from hosted
SLVR: | | | | | | | | | | | | | | | glob 1.1.5 from hosted is locked
SLVR: | | | | | | | | | | | | | | | * select glob 1.1.5 from hosted
SLVR: | | | | | | | | | | | | | | | | html 0.13.2+2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | * select html 0.13.2+2 from hosted
SLVR: | | | | | | | | | | | | | | | | | http 0.11.3+16 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | * select http 0.11.3+16 from hosted
SLVR: | | | | | | | | | | | | | | | | | | http_multi_server 2.0.4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | * select http_multi_server 2.0.4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | http_parser 3.1.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | * select http_parser 3.1.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | io 0.3.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | * select io 0.3.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | isolate 1.1.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | * select isolate 1.1.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | js 0.6.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | * select js 0.6.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | logging 0.11.3+1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | * select logging 0.11.3+1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | matcher 0.12.1+4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | * select matcher 0.12.1+4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | meta 1.1.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | * select meta 1.1.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | mime 0.9.5 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | * select mime 0.9.5 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | mockito 2.2.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | * select mockito 2.2.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | multi_server_socket 1.0.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select multi_server_socket 1.0.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | node_preamble 1.4.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select node_preamble 1.4.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | package_config 1.0.3 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select package_config 1.0.3 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | package_resolver 1.0.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select package_resolver 1.0.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | path 1.5.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select path 1.5.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | plugin 0.2.0+2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select plugin 0.2.0+2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | pool 1.3.4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select pool 1.3.4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | pub_semver 1.3.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select pub_semver 1.3.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | quiver 0.28.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select quiver 0.28.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | shelf 0.7.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select shelf 0.7.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | shelf_packages_handler 1.0.3 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select shelf_packages_handler 1.0.3 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | shelf_static 0.2.7 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select shelf_static 0.2.7 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | shelf_web_socket 0.2.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select shelf_web_socket 0.2.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | sky_engine 0.0.99 from path is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select sky_engine 0.0.99 from path
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | source_map_stack_trace 1.1.4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select source_map_stack_trace 1.1.4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | source_maps 0.10.4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select source_maps 0.10.4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | source_span 1.4.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select source_span 1.4.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | stack_trace 1.9.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select stack_trace 1.9.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | stream_channel 1.6.3 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select stream_channel 1.6.3 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | string_scanner 1.0.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select string_scanner 1.0.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | term_glyph 1.0.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select term_glyph 1.0.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | test 0.12.30+1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select test 0.12.30+1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | analyzer 0.31.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select analyzer 0.31.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | front_end 0.1.0-alpha.9 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select front_end 0.1.0-alpha.9 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | kernel 0.3.0-alpha.9 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select kernel 0.3.0-alpha.9 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | typed_data 1.1.4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select typed_data 1.1.4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | utf 0.9.0+3 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select utf 0.9.0+3 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | vector_math 2.0.5 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select vector_math 2.0.5 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | watcher 0.9.7+6 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select watcher 0.9.7+6 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | web_socket_channel 1.0.6 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select web_socket_channel 1.0.6 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | yaml 2.1.13 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select yaml 2.1.13 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.4.0 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.3.6 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.3.5 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.3.4 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.3.3 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.3.2 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.3.1 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.3.0 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.2.0 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.1.1 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.1.0 of flutter_redux doesn't match 0.4.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_redux_boilerplate 0.0.0 (root) -> flutter_redux 0.4.1 from hosted (flutter_redux)
SLVR: BacktrackingSolver took 0:00:02.239035 seconds.
    | - Tried 1 solutions
    | - Requested 2 version lists
    | - Looked up 1 cached version lists
    | 
FINE: Resolving dependencies finished (2.2s).
ERR : Package flutter_redux has no versions that match 0.4.1 derived from:
    | - flutter_redux_boilerplate depends on version 0.4.1
FINE: Exception type: NoVersionException
FINE: package:pub/src/entrypoint.dart 216                                           Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                                           GetCommand.run
    | package:args/command_runner.dart 194                                          CommandRunner.runCommand
    | package:pub/src/command_runner.dart 167                                       PubCommandRunner.runCommand.<fn>
    | dart:async                                                                    new Future.sync
    | package:pub/src/utils.dart 103                                                captureErrors.<fn>
    | package:stack_trace                                                           Chain.capture
    | package:pub/src/utils.dart 118                                                captureErrors
    | package:pub/src/command_runner.dart 167                                       PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 116                                       PubCommandRunner.run
    | /b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart 8  main
    | ===== asynchronous gap ===========================
    | dart:async                                                                    _Completer.completeError
    | package:pub/src/entrypoint.dart                                               Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                                                    _asyncThenWrapperHelper
    | package:pub/src/entrypoint.dart 194                                           Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                                           GetCommand.run
    | package:args/command_runner.dart 194                                          CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                                    new Future.microtask
    | package:args/command_runner.dart 142                                          CommandRunner.runCommand
    | package:pub/src/command_runner.dart 167                                       PubCommandRunner.runCommand.<fn>
    | dart:async                                                                    new Future.sync
    | package:pub/src/utils.dart 103                                                captureErrors.<fn>
    | package:stack_trace                                                           Chain.capture
    | package:pub/src/utils.dart 118                                                captureErrors
    | package:pub/src/command_runner.dart 167                                       PubCommandRunner.runCommand
---- End log transcript ----
pub get failed (1)
exit code 1`

**Comment by brianegan** [comment]
Hey @ansal-exp, it looks like you might be using a slightly older version of Pub (Pub 2.0.0-dev.16.0), whereas the flutter_redux 0.4.1 requires 2.0.0-dev.28.0 as a minimum version to work!

I'd recommend upgrading flutter to the latest beta channel :) Also, please note: There are some problems with Redux + Dart 2 right now, so I'd actually recommend sticking with the Dart 1 versions for now (Redux + flutter_redux 0.3.6)

**Comment by brianegan** [comment]
For this to work with Dart 2, please use:

  - Latest Flutter beta, dev, or master branch
  - Redux 3.0.0
  - flutter_redux 0.5.0

Please let me know if you run into trouble with that combo!
