### ISSUE TITLE
There is one more motive of failure when it cannot find the StoreConnector.

### ISSUE THREAD

**Issue by marcglasberg** [brianegan/flutter_redux#36]
I got this:

    I/flutter (15445): The following StoreProviderError was thrown building StoreConnector<AppState, _ViewModel>(dirty):
    I/flutter (15445): Error: No StoreProvider<AppState> found. To fix, please try:
    I/flutter (15445):   * Using Dart 2 (required) by using the --preview-dart-2 flag
    I/flutter (15445):   * Wrapping your MaterialApp with the StoreProvider<State>, rather than an individual Route
    I/flutter (15445):   * Providing full type information to your Store<State>, StoreProvider<State> and
    I/flutter (15445):     StoreConnector<State, ViewModel>
    I/flutter (15445): If none of these solutions work, please file a bug at:
    I/flutter (15445): https://github.com/brianegan/flutter_redux/issues/new

Steps to reproduce:

1) Create a file to hold `AppState` named `task_list_redux.dart`, inside of the sandbox package, directory `abc`.
2) In another file in the same `abc` directory, that builds the StoreConnector, import it like this: `import 'package:sandbox/abc/task_list_REDUX.dart';`.

Then it fails.

To solve it, simple change the import to `import 'task_list_REDUX.dart';`.

**Comment by brianegan** [comment]
Great call. I've seen this a couple of times now, but forgot to put it in the error message. I'll do that post-haste!

**Comment by miketheprogrammer** [comment]
@brianegan - I am currently getting `No dynamic found. To fix, please try` on release version.
have you seen this before.

**Comment by brianegan** [comment]
Hrm, I haven't seen that one. I'll try to take a look soon!

**Comment by miketheprogrammer** [comment]
My issue may have been `preview dart 2` related.
