### ISSUE TITLE
Is there a better way to handle nested properties in state?

### ISSUE THREAD

**Issue by AxelMarquez** [brianegan/flutter_redux#37]
For example, I have the following nested state (only left the relevant parts for clarity):
```
class AppState {

   final OpenBook openBook;
}

class OpenBook {

  final bool headerIsFetching;
}
```

&nbsp;
And the reducer:
```
new AppState(

  openBook: new OpenBook(//<- This can be optimized! new instance is built for every cycle regardless of the action
    headerIsFetching: buildFetchingReducer<FetchOpenBookHeaderAction, FetchOpenBookHeaderSucceededAction, FetchOpenBookHeaderFailedAction>(state.openBook.headerFetching, action)
  )  
);
```

&nbsp;
I have thought 2 options: 
1. Encapsulate the instantiation of the OpenBook inside an if that tests for the relevant actions, but this leads to code duplication and it goes against the Open/closed principle (SOLID)
2. Use a switch and for each relevant action create a new OpenBook and initialize only the relevant property, but it feels weird as Dart doesn't have the [Spread operator](https://github.com/dart-lang/sdk/issues/7023) (the three dots in javascript)
3. Flatten the state

Do you have a recommendation?

**Comment by brianegan** [comment]
Heya, sorry about the delay -- somehow missed this notification! Have you played around with the `combineReducers` + `TypedReducer` stuff at all? https://github.com/johnpryan/redux.dart/blob/master/doc/combine_reducers.md in combination with something like a `copyWith` method (https://github.com/brianegan/flutter_architecture_samples/blob/master/example/redux/lib/models/app_state.dart#L23)?

**Comment by AxelMarquez** [comment]
Hello Brian! Sorry for my late reply,

Many thanks for the hints! I ended up using **_copyWith_** and really liked how clear the code looks with this method. Feel free to close this.

Again many thanks, and awesome library! 😊

**Comment by brianegan** [comment]
Sure thing, glad to help, and happy it's working well for ya :)
