### ISSUE TITLE
Auto search on type without having to return

### ISSUE THREAD

**Issue by bowojori7** [brianegan/flutter_redux#53]
Been thinking about this for a while now and it's been mind boggling coming up with how to implement automatically searching when a user types with flutter_redux. 
I found this repo https://github.com/brianegan/dart_redux_epics and I feel like this is the correct way to do it after checking out the readme file. 
My questions are:
1. Can redux_epics including rxdart be combined with flutter_redux for this use case? If yes how will I go about doing this??
2. Is there a way to achieve what I'm trying to with just flutter_redux and plain middlewares? If yes, help would be greatly appreciated.

Thank you.

**Comment by brianegan** [comment]
Hey @bowojori7, did this solve your issue and help ya out? Let me know or if it's cool to close this out :)

**Comment by bowojori7** [comment]
I'm so sorry @brianegan. I've been so busy this past week. Not had time to check. I'll try this soon and get back to you. 
So sorry.
Thanks for the awesome help.

**Comment by brianegan** [comment]
Heya @bowojori7 -- I'll go ahead and close this issue for now, but please feel free to write back if ya need more help :)
