### ISSUE TITLE
TextField keyboard pops up and disappears with  StoreConnector builder. 

### ISSUE THREAD

**Issue by Abgaryan** [brianegan/flutter_redux#58]
The screen is stateless, I am storing widget states in the Store.

**Comment by brianegan** [comment]
Hey there! Sorry -- somehow missed this one. This problem often comes up if you're creating & recreating the `TextEditingController`. Often times, with TextFields, you'll want to build a `StatefulWidget` that initializes the `TextEditingController` only once, rather than creating a new one on each build.

**Comment by Abgaryan** [comment]
Thank you @brianegan for the comment, my goal was to avoid using stateful widget instead to have a stateless widget with a redux state.

**Comment by brianegan** [comment]
Yah, in many cases you don't need to use `StatefulWidgets`, but there are just a few cases where ya have to use a `StatefulWidget` to hold onto certain Flutter classes that need to be retained for each build. This includes things like `TabControllers`, `TextEditingControllers`, etc... If you recreate these things each time in the ViewModel you'll run into trouble.

**Comment by brianegan** [comment]
Hey @Abgaryan :) Did my advice help at all, or do ya have any follow-up Qs?

**Comment by Abgaryan** [comment]
Hey @brianegan, Thank you very much for your advice, I changed the screen from stateless to stateful now it works.

**Comment by noobiek** [comment]
> Yah, in many cases you don't need to use `StatefulWidgets`, but there are just a few cases where ya have to use a `StatefulWidget` to hold onto certain Flutter classes that need to be retained for each build. This includes things like `TabControllers`, `TextEditingControllers`, etc... If you recreate these objects each time in the ViewModel you'll run into trouble.

Hi Brian,
What doyou mean when you say "If you recreate these objects each time in the ViewModel you'll run into trouble"?
Currently I am making a small app with infinite list (with LiveView.builder), and for each item I recreate TextEditingController in onInit() and dispose in onDispose(). What can possibly go wrong?
