### ISSUE TITLE
Examples 404

### ISSUE THREAD

**Issue by jaumard** [brianegan/flutter_redux#60]
It redirect to a gitlab instance with message: 
The page could not be found or you don't have permission to view it.

Simple and Github search

**Comment by brianegan** [comment]
Oh dang, thanks for the heads up! I'll fix that up.

**Comment by brianegan** [comment]
Hey, thanks again, pushed up a fix!

**Comment by jaumard** [comment]
My pleasure ;) thanks for the fix
