### ISSUE TITLE
Why we need to pass the String type in StoreConnector ?

### ISSUE THREAD

**Issue by fadhilkemal** [brianegan/flutter_redux#67]
### I found this on the example

https://github.com/brianegan/flutter_redux/blob/dfc42c34d2102bdf896bd745e5e13c868a5ad652/example/counter/lib/main.dart#L70

```
new StoreConnector<int, String>(
                  converter: (store) => store.state.toString(),
                  builder: (context, count) {
                    return new Text(
                      count,
                      style: Theme.of(context).textTheme.display1,
                    );
                  },
                )

```

### 1. Is there any performance Issue if I change the second **Type Parameter from String to Int ?**

```
new StoreConnector<int, int>(
                  converter: (store) => store.state,
                  builder: (context, state) {
                    return new Text(
                      "${state}",
                      style: Theme.of(context).textTheme.display1,
                    );
                  },
                )

```

### 2. Because I have another flutter-redux example that looks like this

```

StoreConnector<AppState, int>(
                converter: (store) => store.state.itemCount,
                builder: (context, count) {
                  return Text(
                    "$count",
                    style: Theme.of(context).textTheme.display1,
                  );
                },
              ),


```

then I changed it to this

```
StoreConnector<AppState, AppState>(
                converter: (store) => store.state,
                builder: (context, state) {
                  return Text(
                    "${state.itemCount}",
                    style: Theme.of(context).textTheme.display1,
                  );
                },
              ),

```

**Comment by brianegan** [comment]
The second type parameter provides Type information about what kind of "ViewModel" you're extracting from the Store. If you didn't provide the second type, it would have to be `dynamic` or `Object`, which means you wouldn't have the proper type information in the `builder` function, nor would you have any type checking to ensure the `converter` function returns a value of the Type you expect.

If you want to pass through just the state of the Store, it's not the approach I would take, but there's nothing stopping you from doing it.

Generally I use the `converter` to gather all the data I need for the `builder` function, so I don't need to do any work inside the builder function other than create a Widget with the values I've extracted inside the `converter`.
