### ISSUE TITLE
StoreConnector distinct default value

### ISSUE THREAD

**Issue by smiLLe** [brianegan/flutter_redux#68]
Hi,
i am using built_value which implements == and hashcode automatically. So whenever i use the StoreConnector i usually want distinct to be true.

What do you guys think about having something like a static StoreConnector.distinctDefault  value 
which then will be used as the default value in the constructor?

Oh and thanks for this great lib :)

**Comment by smiLLe** [comment]
Hey, have a great vacation! :)

I also don't like the idea of having a global/static/mutable property.
What about subclassing StoreConnector to something like DistinctStoreConnector. It would expose the same constructor without the distinct property.

**Comment by brianegan** [comment]
Hey all :) Back from vacay.

Aight, so I could create a `DistinctStoreConnector`, but I wonder if that will save much typing overall? Another option: I could also create a `factory`, like `StoreConnector.distinct(...)`. However, I'm not sure either of these will save much typing int the end.

E.g. `DistinctStoreConnector(...)` or `StoreConnector.distinct` aren't much shorter than `StoreConnector(distinct: true, ...)`.

Unfortunately, I feel like providing a Global would save the most amount of typing. What are your thoughts?

**Comment by smiLLe** [comment]
Hey :) Sorry for the late response, i also was on vacation :)

I agree with StoreConnector.distinct - And you must still _remember_ to use the factory.
Using a Global just does not feel good :( Let's close this Issue and wait if other people asking for the same feature?

**Comment by brianegan** [comment]
Cool, thanks @smiLLe :) Hope ya had a good vacay!
