### ISSUE TITLE
Model updates but widget does not redraw.

### ISSUE THREAD

**Issue by bradintheusa** [brianegan/flutter_redux#7]
Hi

This works fine
```
new Text(viewModel.game.duration.toString())
```
but this does not. 
```
new Text(viewModel.game.formattedDuration(viewModel.game.duration),
```

Am I doing this wrong?  Should I be formatting my duration inside the reducer?

(I'm on a slightly older version so I'm updating now)

**Comment by brianegan** [comment]
Hey hey :) Thanks for the report! Sorry about the delay, was on vacation for a bit.

Interesting case! Could you please attach a bit more code so I can see how you're creating your ViewModel and how you're using the StoreConnector? 

Debugging thoughts:

  1. Could you please put a few `print` statements throughout your code to see what's getting called and what isn't? Places I'd put `print` statements: Your Reducer, the `converter` function, and the `builder` function and let me know where it stops printing? For example, if your reducer prints out a statement, but the `converter` function does not print anything, it could be an indicator that the `StoreConnector` isn't properly hooked up to a `Store`.
  2. Are you setting `distinct` to `true` in your `StoreConnetor` constructor? If so, have you properly implemented the `==` method on your ViewModel?

Thanks again for the report!

**Comment by bradintheusa** [comment]
Thanks.

This was entirely my fault.  The code works as expected.

**Comment by brianegan** [comment]
No worries!
