### ISSUE TITLE
Error: No StoreProvider<dynamic> found. 

### ISSUE THREAD

**Issue by pierrederuel** [brianegan/flutter_redux#70]
Hi,

I am using this boilerplate (https://github.com/FranPitri/flutter_redux_boilerplate) and when I try to access the store object to dispatch an action, for example

`StoreProvider.of(context).dispatch(new UserLoginFailure("Ca marche pas"));`

 I get this error:

> Error: No StoreProvider<dynamic> found. To fix, please try: 
> flutter:   * Using Dart 2 (required) by using the --preview-dart-2 flag
> flutter:   * Wrapping your MaterialApp with the StoreProvider<State>,
> flutter:   rather than an individual Route
> flutter:   * Providing full type information to your Store<State>,
> flutter:   StoreProvider<State> and StoreConnector<State, ViewModel>
> flutter:   * Ensure you are using consistent and complete imports.
> flutter:   E.g. always use `import 'package:my_app/app_state.dart';
> I think this boilerplate project respects these requirements...

Have you got an idea?

Thanks a lot for your work,

Pierre

**Comment by brianegan** [comment]
Heya @pierrederuel -- did this solve your problem?

**Comment by pierrederuel** [comment]
Hey Brian, sorry for replying so late but I had an issue with my internet connection. Yes the problem is solved, thanks a lot for your reply while you are on vacation!
