### ISSUE TITLE
How to handle normalized state?

### ISSUE THREAD

**Issue by KammererTob** [brianegan/flutter_redux#73]
Hey. First off: Great plugin, i really like working with it.
To keep my App as performant as possible i was reading about normalizing app state for relational data:
https://redux.js.org/recipes/structuringreducers/normalizingstateshape

Now i was wondering how this would be achieved in flutter. I have a state which has a List of objects, which are used to render widgets. Single elements inside the List can dynamically change (by async events through sockets, or user input). My current implementation would lead to a complete rerender of the list. Here is some example code:

```
class CompetitionState {
 final LoadingStatus status;
 final Competition competition;
}

class Competition {
 final List<Competitor> competitors;
}

class CompetitionPageViewModel {
  final LoadingStatus status;
  final Competition competition;
}
```

In my view i use a StoreConnector like this:

```
return StoreConnector<AppState, CompetitionPageViewModel>(
      distinct: true,
      converter: (store) => CompetitionPageViewModel.fromStore(store),
      builder: (context, viewModel) => CompetitionPageContent(viewModel)
    );
```

As you can see this would lead to the whole page to be rerendered if a single `Competitor` changes inside the state, wouldn't it?

Now i am currently thinking about trying a similar approach as they have outlined in the documentation, but i am unsure if this is really the best way to go. It looks something like this:

```
// entites_state.dart
class EntitiesState {
  final CompetitorsEntity competitors = new CompetitorsEntity();
}

// competitors_entity.dart
class CompetitorsEntity {
  Map<int, Competitor> byId;
  Set<int> allIds;
}
```

// competitors_reducer.dart
```
final competitorsReducer = combineReducers<CompetitorsEntity>([
  TypedReducer<CompetitorsEntity, ReplaceCompetitorsAction>(_replaceCompetitors),
  TypedReducer<CompetitorsEntity, ReplaceCompetitorAction>(_replaceCompetitor)
]);

CompetitorsEntity _replaceCompetitors(CompetitorsEntity entity, ReplaceCompetitorsAction action) {
  entity.allIds.clear();
  entity.byId.clear();
  for (Competitor competitor in action.competitors) {
    entity.allIds.add(competitor.id);
    entity.byId[competitor.id] = competitor;
  }
  return entity;
}

CompetitorsEntity _replaceCompetitor(CompetitorsEntity entity, ReplaceCompetitorAction action) {
  entity.allIds.add(action.competitor.id);
  entity.byId[action.competitor.id] = action.competitor;
  return entity;
}
```

With this approach the `competitors_entity.dart` is not  immutable. If i make it immutable and always copy the whole state in those reducers, would this lead to **all** widgets which are connected to be rerendered? And more specifically would i even be able to use a StoreConnector to connect to a single competitor, so that only one Widget gets rerendered?
Any advice or guide in the right direction would be appreciated!

**Comment by KammererTob** [comment]
I may have found a way to normalize the state and prevent rerendering the whole list on single entity changes. Basically my state now looks like this:

```
class AppState {
    final Session session;
    final CompetitionsState competitions;
    final CompetitorsState competitors;
}

class CompetitionsState {
   final LoadingStatus status;
   final Map<int, Competition> byId;
   final List<int> sortedIds;
}

class CompetitiorsState {
   final LoadingStatus status;
   final Map<int, Competitor> byId;
   final List<int> sortedIds;
}
```
And since the view model decides if a widget gets rebuild or not (at least with distinct: true), i connect the pages like this:

```
class CompetitorsPageViewModel {
  final LoadingStatus status;
  final List<int> competitorIds;

  CompetitorsPageViewModel fromStore(AppState store) {
      return CompetitorsPageViewModel(
          status: store.competitors.status,
          competitorIds: store.competitors.sortedIds
      );
   }
}

class CompetitorsPage extends StatelessWidget {
    Widget build(BuildContext context) {
        return StoreConnector<AppState, CompetitorsPageViewModel>(
           distinct: true,
           converter: (store) => CompetitorsPageViewModel.fromStore(store),
           builder: (context, viewModel) => CompetitiorsPageContent(viewModel)
        );
    }
}

// CompetitorsPageContent creates a ListView consisting of CompetitorTile, 
// while passing the id to the child widget


class CompetitorTile extends StatelessWidget {
    final int competitorId;

    CompetitorTile(this.competitorId);

    Widget build(BuildContext context) {
        return StoreConnector<AppState, Competitor>(
           distinct: true,
           converter: (store) => store.state.competitors.byId[this.competitorId],
           builder: (context, competitor) => CompetitiorsTileContent(competitor)
        );
    }
}
```

If both the `equal` and `hashCode` methods are well defined in the `CompetitorsPageViewModel` and `Competitor` , this has the following benefits:

1. The complete List only gets rerendered if an element gets added or removed or the order inside the `sortedIds` changes.
2. A single element gets rerendered if a property inside the entity changes, but this should no longer trigger a complete list re-render.

Sadly it also still has some drawbacks:

1. We need to maintain both the Map and the List inside the states, at least when we add or remove items. - i did not find a satisfactory way to ideally do this inside the view model.
2. For each different sorting of entities we would need an additional list of ids inside the states which now would also need to be maintained.

I feel like there should still be a better solution to this.

**Comment by DizWARE** [comment]
You are correct... Maintaining this duplicate data as it changes is definitely not ideal. Probably could tun into a nightmare depending on the size of your app.

What you should do is write a suite of selectors that will gather and perform all the data transformations you need to give you the data you need, where you need it. There is no update to the store when using a selector, but it allows you to use the store to get normalized or transformed data safely. Adding equality checks in your view models will then reduce the number of times your widget updates based on this information.

So an example is, instead of keeping track of a sorted competitors list, you write a selector:

```dart
getSortedCompetitors(Store<AppState> store, Function sortMethod) {
    return store.state.competitors.sort(sortMethod);
}

getSortedCompetitorIds(Store<AppState> store, Function sortMethod) {
    return getSortedCompetitors(store, sortMethod).map(value => value.id);
}
```

or getting a specific competitor:

```dart
getCompetitorById(Store<AppState> store, int id) {
    return store.state.competitors..firstWhere((value) => value.id == id);
}
```

Your view models then look something like this:

```dart
import "../selectors/competitors.dart" show getCompetitorById, getSortedCompetitorIds;

class CompetitorsPageViewModel {
  final LoadingStatus status;
  final List<int> competitorIds;

  CompetitorsPageViewModel fromStore(Store<AppState> store) {
      return CompetitorsPageViewModel(
          status: store.competitors.status,
          competitorIds: getSortedCompetitorIds(store, () => ~sortStuff~)
      );
   }
}

class CompetitorTile extends StatelessWidget {
    final int competitorId;

    CompetitorTile(this.competitorId);

    Widget build(BuildContext context) {
        return StoreConnector<AppState, Competitor>(
           distinct: true,
           converter: (store) => getCompetitorById(store, competitorId),
           builder: (context, competitor) => CompetitiorsTileContent(competitor)
        );
    }
}

```

**Comment by KammererTob** [comment]
Thanks for your answer. I am going a similar route now where my competition only holds all the expected competitor ids and all competitors are inside another branch of the state (and accessable by id). This allows me to keep my state clean and create something like a database view into my state by using selectors as you suggested.

This also allows me to re-render the whole list if the order changes (by having changes inside the view-model based on the list of ids) and also to only re-render certain competitors if they change (based on the equals method inside each competitor).

I am pretty happy overall now, except for one thing:
Where to put a loading status? I could put it inside each competition, but when i load a list of competitions i don't know beforehand how many/what competitions are being loaded and thus i cannot access the state while they are loaded. I could put it inside the parent (holding **all** the competitions), but that would potentially lead to a loading status for competitions which are already loaded.
I have circumvented the problem for competitors, because i already load all expected ids when i load the competitions, and thus i could already create the state with a loading status for each competitor. This would also allow me to use Streams and then show a loading symbol for individual competitors and display them one by one as they come in. I guess for an indeterminate number of entities to be loaded i could create placeholder states and fill them as the entites stream in, and then remove potential excess states after the stream is finished.

**Comment by brianegan** [comment]
Hey @KammerTob -- glad ya like the library and sorry for the delayed response! Could you help describe this a bit more?

"but when i load a list of competitions i don't know beforehand how many/what competitions are being loaded and thus i cannot access the state while they are loaded"

It sounds to me like the loading state is made up of two pieces: Fetching the `List<Competiton>` and fetching the details for each Competition after that's loaded. Is that correct?

If so, you could make a selector that returns a bool, something like this (kinda pseudo-code, would have to adjust it to your state):

`bool competitionsLoading(Store<State> store) => store.competitions.loading || store.competitions.any((competition) => competition.loading));`

**Comment by KammererTob** [comment]
@brianegan Yes you understood correctly and your selector makes sense when you need to load *more* information later on. 

This does however not work for the general case of: "Get all competitions which belong to a specific event". I would not have any competitions in my store yet and thus would also not know beforehand how many competitions this query will return. This means that i need the loading status on the state which holds *all* competitions and can not display a loading status on each competition and display them as they come in. I can however just show that my stream is not finished yet (by indicating it with a global loading status) and then just display the competitions one after another until the stream is finished. It is not really a "problem" with redux anymore though, because no library can predict the future :)

I think most of my problems with a normalized state are resolved by now! Thanks for your time and this library!

**Comment by brianegan** [comment]
Sure thing! Thanks for using it :)

  > "Get all competitions which belong to a specific event."

Ah, gotcha. So Events contain competitions. In that case, could you store an `Event` object, that contains a `competitionsLoading` as well as a `List<int> competitionIds` or `Set<int>` ? Then, when you show an event, you could dispatch a `LoadEventAction` to fetch the list of competitions and their data. When that's complete, set the `competitionsLoading` bool to false? 

Not sure if that would work or not, feels like one of those "harder problems" that's a bit easier to chat about than describe in text boxes haha.

  > because no library can predict the future :)

Yet... :P

Thanks again for using the lib! Glad you're liking it!
