### ISSUE TITLE
Add example to OnDidChangeCallback docs

### ISSUE THREAD

**Issue by ejabu** [brianegan/flutter_redux#74]
https://github.com/brianegan/flutter_redux/blob/dfc42c34d2102bdf896bd745e5e13c868a5ad652/lib/flutter_redux.dart#L108

**Comment by brianegan** [comment]
Hey there -- thanks for writing in! I'll add some docs for that function.

**Comment by subhash279** [comment]
Hi,
regarding OnDidChangeCallback, is there a way to detect if only particular fields have updated like the way you can do in react-redux using (prevProps.field !== props.field)?
Also when a field does get updated, is there a way to get its previous value(again similar to prevProps.field)?

**Comment by brianegan** [comment]
Added Example and `previousViewModel` to onDidChange
