### ISSUE TITLE
Add example to OnWillChange docs

### ISSUE THREAD

**Issue by ejabu** [brianegan/flutter_redux#75]
https://github.com/brianegan/flutter_redux/blob/dfc42c34d2102bdf896bd745e5e13c868a5ad652/lib/flutter_redux.dart#L105

is there any example of using this ?

I got stressed Out since my TabBar always rebuild after dispatching a filter. Since then, the TabController animation which shows the current tab index will never be shown

**Comment by MihaMarkic** [comment]
@brianegan Is there a way to compare the old and new viewmodel? Or old and new store?
For example: In @DizWARE sample, the snack bar would appear each time the widget is rebuilt. Something like 

```dart
if (viewModel.wasSuccessful && !viewModel.wasSuccessful) {
    // show SnackBar
}
```

would be better I think. Or how do you handle one time property changes like this?

**Comment by Nolence** [comment]
In React, I used to avoid diffing states altogether by simply having my actions return a promise and then chaining a `.then` to them to show any alerts, but I can't find a simple example that does this with `flutter_redux` and `flutter_redux_thunk`.

Either way, I'd love to know if anyone has found a workaround for showing the snack bar just once.

**Comment by brianegan** [comment]
OnWillChange now supports new and old viewmodel, also adde example to latest version.
