### ISSUE TITLE
How to navigate in a CupertinoApp

### ISSUE THREAD

**Issue by enyo** [brianegan/flutter_redux#79]
With a `MaterialApp` you can provide the `navigatorKey` and use that in your middleware to redirect the user if necessary.

But `CupertinoApp` doesn’t have a `navigatorKey`.

Now what we are doing is to add the `context` to the action so we have access to it in the middleware, but this seems very wrong.

Do you have a proposal on how to do this best?

**Comment by brianegan** [comment]
Hrm, that's a problem indeed.

 Lemme see if I can follow up with the Flutter team on why they don't provide a `navigatorKey` in the same way... Feels like a problem more folks are going to run into!

**Comment by brianegan** [comment]
And looks like ya beat me to it :) https://github.com/flutter/flutter/issues/22258

I'll close this one out, since I don't think this library should offer a workaround to the underlying problem, and now the underlying problem is solved :) 

Thanks for the report!

**Comment by enyo** [comment]
Indeed @brianegan . Sorry, I completely forgot to close this issue! Thanks for looking into it.
