### ISSUE TITLE
distinct in debounce duration

### ISSUE THREAD

**Issue by ColorFuzzy** [brianegan/flutter_redux#84]
Is there a way to distinct message in a limit debounce duration.

For example:
message flow: a(200ms) -> a(300ms) -> a(800ms)  => if distinct , only one message will be delivered;

if distinct in a limit debounce duration, like 600ms => two message will be delivered, only the middle a(300ms) will not deliver.

1. if distinct message in a limit debounce duration
2. => every different message will be delivered
3. => if two same message triggered in a limit debounce, only one will be delivered

**Comment by brianegan** [comment]
Not out of the box -- for that use-case, you could use a `StreamBuilder` + grab the store's Change stream from the Widget heirarchy via `StoreProvider.of<AppState>(context).onChange`. You could then transform that `onChange` stream in any way ya need!

**Comment by ColorFuzzy** [comment]
> Not out of the box -- for that use-case, you could use a `StreamBuilder` + grab the store's Change stream from the Widget heirarchy via `StoreProvider.of<AppState>(context).onChange`. You could then transform that `onChange` stream in any way ya need!

As there is no out of the box solution, I'll keep the last message and timestamp.
