### ISSUE TITLE
Who's using flutter_redux in production?

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [brianegan/flutter_redux#86]
Similar to this:
reactiveui/ReactiveUI#979
PrismLibrary/Prism#1016
orientechnologies/orientdb#4806

Use the following template:
Drag and drop a screenshot or two onto the comment.

Author:
Website:

Apple:
Android:

**Your opinion**
Version: ?
Years of experience: ?
Goods: ?
Bads: ?
Problems: ?

If open source
Source Code (!):

Thank you very much!

**Comment by Taym95** [comment]
A lot of companies are using this library on production, I think the library needs more support.
