### ISSUE TITLE
Hot restart crashes

### ISSUE THREAD

**Issue by arkanmgerges** [brianegan/flutter_redux#88]
Hi,
I really don't know if this issue is related to redux or dart + flutter, but I will write it here just to let you know.
I'm having this issue, I want to change the theme dynamically using redux. It is working but the problem is the second or third time I hot restart the app, it will crash.

```sh
// initializing the store is done, I just want to keep the code snippet small
// in main.dart

class MainApp extends StatefulWidget {
  final Store<AppState> store;
  MainApp({this.store});

  @override
  State<StatefulWidget> createState() {
    return _MainApp(store: store);
  }
}

class _MainApp extends State<MainApp> {
  final Store<AppState> store;

  _MainApp({this.store});

  @override
  Widget build(BuildContext context) {
    return new StoreProvider<AppState>(
        store: store,
        child: StoreBuilder<AppState>(builder: (BuildContext context, store) {
          return MaterialApp(
...etc
```
The above code will crash if you put StoreBuilder in that way, after you hot restart 2nd or 3rd time.
If you also use StoreConnector, it will also have the same crash

If you remove StoreBuilder above, the app will not crash on hot restart.

I don't know really if this issue related to flutter_redux or not
I also mentioned this on [Application crashes on hot restart](https://github.com/flutter/flutter/issues/19590)

Thanks

**Comment by brianegan** [comment]
Hey there -- thanks for reporting!

I think I'm gonna close this one, since I don't think Redux is the source of this bug. Overall, Hot Reload has been having some problems lately (as you saw on Flutter's github), and I've seen a lot of crashes on many projects lately after 2-3 reloads :/ 

If the original issue is resolved, and this keeps happening, let's reopen it.
