### ISSUE TITLE
Subscribe to stream in middleware

### ISSUE THREAD

**Issue by ronmany** [brianegan/flutter_redux#90]
I have a middleware that needs to response to event from the hardware.
this HW events needs to fire different actions that changes the redux state.
I already have a stream setup. How would I subscribe to this stream in the middleware?

Thank you

**Comment by brianegan** [comment]
Hey there -- sorry for the delay. Very busy work/travel times. 

For this case, I'd recommend checking out the redux_epics package. It will provide a nice way to merge Streams with Middleware.

In your case, you could either supply the Stream to your Middleware / Epic function, or dispatch an action that contains the Stream.

Once the middleware receives the Stream, it can start listening and dispatch actions!

Something like this:

```
class MyStreamMiddleware extends MiddlewareClass<AppState> {
    final Stream<String> myStream;
    StreamSubscription<String> _subscription;

    MyStreamMiddleware(this.myStream);

   @override
    void call(Store<AppState> store, dynamic action, NextDispatcher next) {
      if (action is ListenToStreamAction) {
        _subscription = stream.listen((data) {
          store.dispatch(DataReceivedAction(data));
        })
      } else if (action is StopListeningAction) {
        _subscription?.cancel();
      }

      next(action);
    }
}
```
