### ISSUE TITLE
Update a widget which must use stateful

### ISSUE THREAD

**Issue by YLoveX** [brianegan/flutter_redux#95]
Hi, 

I'm using a StatefulWidget CardsHorizonRoller under the storeConnector, 
```
Widget charts() {
    return StoreConnector<AppState, ChartViewModel>(converter: (store) {
      return ChartViewModel.from(store);
    }, builder: (BuildContext context, ChartViewModel chartViewModel) {
      List<Widget> widgets = [];
      //construct widgets use chartViewModel
      return CardsHorizonRoller(
        widgets,
        cardsFraction: 0.9,
        horizonSpace: 5,
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return charts();
  }
```

and this will not update the CardsHorizonRoller after i update the 'chartViewModel', distinct is true. 
In CardsHorizonRoller I use a TabController which must extends from a statefulWidget....

Which part do I missed?

Anyone who can help me? Thank you very much!

**Comment by vvasc** [comment]
CardsHorizonRoller will be updated when your state tree has been updated. In your code chartViewModel is the way to dispatch actions, and in your reducers this actions will affect the state tree
