### ISSUE TITLE
async TypedMiddleware?

### ISSUE THREAD

**Issue by MihaMarkic** [brianegan/flutter_redux#96]
It'd be nice to have async versions of TypedMiddleware.

```dart
return (Store<AppState> store, LoginResultAction action, Future<NextDispatcher> next) async {
    await next(action);
    ....
```
So the next dispatcher can be awaited.
Does that make sense?

**Comment by brianegan** [comment]
Hey there -- sorry, thought I'd put in an answer to that Q!

Could you describe the use-case a bit more to see if we can find a good solution?

Overall, I definitely understand why this would be helpful, but this would essentially break the fundamental promise that Redux gives you: Actions are dispatched and reduced *synchronously*.

This means you can do `store.dispatch` on one line, and the very next line `store.state` will be in the expected state given the update. If we made `next` async, this means any action in the chain could delay the reducer from running synchronously, and I think that will lead to a lot more headaches.

**Comment by MihaMarkic** [comment]
I see. I was thinking about what if you have to execute an async operation within middleware, such as if you want to persist the current state and the persistence method is asynchronous? Or perhaps you need some other async method to proceed? Isn't this something that middleware should support? Or not?

**Comment by brianegan** [comment]
It certainly is! The main trick: You can't use `async/await`, but you can still do `myFuture.then(...).then(...)` or listen to Streams just fine.

If you'd like to use `async/await` features, lot of times I'll use the `redux_epics` package. It's kind of like Stream-based middleware, and it supports `async*` functions which allow you to run `async/await` calls.

https://pub.dartlang.org/packages/redux_epics

**Comment by MihaMarkic** [comment]
Basically calling async methods without waiting, I guess it makes sense.
